version: '3.4'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: backend-db
    restart: always
    networks:
      - nodenet
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=pass123

  app:
    build: 
      context: node
    container_name: node-app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 --timeout 20s docker-entrypoint.sh index.js
    networks:
      - nodenet
    ports:
      - 3000
    depends_on:
      - db

  nginx:
    build: 
      context: nginx
    container_name: frontend-nginx
    restart: always
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node-app

networks:
  nodenet:
    driver: bridge

volumes:
  mysql:
