name: ci-golang-workflow
on:
  push:
    branches:
      - cicdgithub

strategy:
  matrix:
    go: ['1.14','1.15','1.16'] # Aqui colocamos as versoes de teste

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Atualiza os dados do repositorio para dentro do container
      - uses: actions/setup-go@v2 # Organiza os dados para rodar o golang
        with:
          go-version: ${{ matrix.go }} # colocamos matrix.key que no nosso caso foi escolhido a matrix go.
      #- run: go test
      - run: go run ./cicdgithub/math.go
