name: ci-golang-workflow
on:
  push:
    branches:
      - cicdgithub

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Atualiza os dados do repositorio para dentro do container
      - uses: actions/setup-go@v2 # Organiza os dados para rodar o golang
        with:
          go-version: 1.15
      #- run: go test
      - run: go run ./cicdgithub/math.go
